name: CI

on:
  workflow_dispatch:        # <-- lets you run it by button
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: sbt
      - name: Build and Test
        run: sbt -v test
